# Generated by Django 4.1 on 2022-08-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_person_work_employer_person_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cooperation',
            field=models.ManyToManyField(null=True, to='main.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(null=True, to='main.employer'),
        ),
        migrations.AlterField(
            model_name='person',
            name='languages',
            field=models.ManyToManyField(null=True, to='main.languages'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(null=True, to='main.skills'),
        ),
    ]
