# Generated by Django 4.1 on 2022-08-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_company_cooperation_alter_company_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cooperation',
            field=models.ManyToManyField(blank=True, to='main.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(blank=True, to='main.employer'),
        ),
        migrations.AlterField(
            model_name='person',
            name='languages',
            field=models.ManyToManyField(blank=True, to='main.languages'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(blank=True, to='main.skills'),
        ),
    ]
