# Generated by Django 4.1 on 2022-08-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_company_cooperation_alter_company_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company_id',
        ),
    ]
